version: "3.9"

services:
  app:
    build: .
    container_name: ada_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  bot:
    build: .
    container_name: ada_bot
    restart: always
    env_file:
      - .env
    environment:
      ADA_API_URL: http://app:8000
    depends_on:
      - app
    volumes:
      - .:/app
    command: python -m bot.telegram_bot